FROM alpine:latest

RUN apk add --no-cache curl git zsh zsh-theme-powerlevel10k fzf bash unzip shadow

SHELL ["/bin/zsh", "-c"]

RUN mkdir -p /root/.local/share/zsh/plugins && \
    git clone https://github.com/zsh-users/zsh-autosuggestions /root/.local/share/zsh/plugins/zsh-autosuggestions && \
    git clone https://github.com/zsh-users/zsh-syntax-highlighting /root/.local/share/zsh/plugins/zsh-syntax-highlighting && \
    ln -s /usr/share/zsh/plugins/powerlevel10k /root/.local/share/zsh/plugins/

COPY .p10k.zsh /root/.config/zsh/.p10k.zsh

RUN echo 'export ZSH_THEME="powerlevel10k/powerlevel10k"' > /root/.zshrc && \
    echo 'source /root/.config/zsh/.p10k.zsh' >> /root/.zshrc && \
    echo 'source /usr/share/zsh/plugins/powerlevel10k/powerlevel10k.zsh-theme' >> /root/.zshrc && \
    echo 'autoload -Uz compinit && compinit' >> /root/.zshrc && \
    echo 'source /root/.local/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh' >> /root/.zshrc && \
    echo 'source /root/.local/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh' >> /root/.zshrc && \
    echo '[ -f /usr/share/fzf/key-bindings.zsh ] && source /usr/share/fzf/key-bindings.zsh' >> /root/.zshrc && \
    echo '[ -f /usr/share/fzf/completion.zsh ] && source /usr/share/fzf/completion.zsh' >> /root/.zshrc

RUN curl -fsSL https://bun.sh/install | bash && \
    echo 'export BUN_INSTALL="$HOME/.bun"' >> /root/.zshrc && \
    echo 'export PATH="$BUN_INSTALL/bin:$PATH"' >> /root/.zshrc && \
    apk del bash

RUN chsh root -s /bin/zsh

WORKDIR /workspace/frontend

CMD ["zsh"]
