networks:
  dev_network:
    driver: bridge

volumes:
  pg-data:
    driver: local
  minio-data:
    driver: local

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
    container_name: backend
    networks: 
      - dev_network
    volumes:
      - .:/workspace:cached
    env_file:
      - ./backend/.env.dev
    command: sleep infinity
    depends_on:
      - pg
      - minio
    ports:
      - "8080:8080"
      - "5005:5005"
  
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    container_name: frontend
    env_file:
      - ./frontend/.env.dev
    networks: 
      - dev_network
    command: sleep infinity
    volumes:
      - .:/workspace:cached
  
  pg:
    image: postgres:latest
    env_file:
      - ./backend/.env.dev
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks: 
      - dev_network
    ports:
      - "5432:5432"
  
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    container_name: minio
    env_file:
      - ./backend/.env.dev
    volumes:
      - minio-data:/data
    networks: 
      - dev_network
    ports:
      - "9000:9000"
      - "9001:9001"
    command: >
      server /data --console-address ":9001"
