networks:
  dev_network:
    driver: bridge

volumes:
  pg-data:
    driver: local

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    networks: 
      - dev_network
    volumes:
      - .:/workspace:cached
    env_file:
      - ./backend/.env.dev
    command: sleep infinity
    depends_on:
      - pg
    ports:
      - "8080:8080"
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    env_file:
      - ./frontend/.env.dev
    networks: 
      - dev_network
    command: sleep infinity
    volumes:
      - .:/workspace:cached
  
  pg:
    image: postgres:latest
    env_file:
      - ./backend/.env.dev
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks: 
      - dev_network
    ports:
      - "5432:5432"

  