FROM maven:3.9.9-eclipse-temurin-21-alpine

RUN apk add --no-cache curl git zsh zsh-theme-powerlevel10k fzf bash unzip shadow wget

SHELL ["/bin/zsh", "-c"]

RUN mkdir -p /root/.local/share/zsh/plugins && \
    git clone https://github.com/zsh-users/zsh-autosuggestions /root/.local/share/zsh/plugins/zsh-autosuggestions && \
    git clone https://github.com/zsh-users/zsh-syntax-highlighting /root/.local/share/zsh/plugins/zsh-syntax-highlighting && \
    ln -s /usr/share/zsh/plugins/powerlevel10k /root/.local/share/zsh/plugins/

COPY .p10k.zsh /root/.config/zsh/.p10k.zsh

RUN echo 'export ZSH_THEME="powerlevel10k/powerlevel10k"' > /root/.zshrc && \
    echo 'source /root/.config/zsh/.p10k.zsh' >> /root/.zshrc && \
    echo 'source /usr/share/zsh/plugins/powerlevel10k/powerlevel10k.zsh-theme' >> /root/.zshrc && \
    echo 'autoload -Uz compinit && compinit' >> /root/.zshrc && \
    echo 'source /root/.local/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh' >> /root/.zshrc && \
    echo 'source /root/.local/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh' >> /root/.zshrc && \
    echo '[ -f /usr/share/fzf/key-bindings.zsh ] && source /usr/share/fzf/key-bindings.zsh' >> /root/.zshrc && \
    echo '[ -f /usr/share/fzf/completion.zsh ] && source /usr/share/fzf/completion.zsh' >> /root/.zshrc && \
    wget https://github.com/google/google-java-format/releases/download/v1.17.0/google-java-format-1.17.0-all-deps.jar -O /usr/local/bin/google-java-format.jar && \
    alias google-java-format="java -jar /usr/local/bin/google-java-format.jar"


RUN chsh root -s /bin/zsh

ENTRYPOINT ["/usr/local/bin/mvn-entrypoint.sh"]
CMD ["mvn spring-boot:run -Dspring-boot.run.profiles=dev"]